window.translations_en = {
    "user_guide": "User Guide v1",
    "nav_intro": "Introduction",
    "nav_dashboard": "Dashboard",
    "nav_profile": "Profile",
    "nav_accounts": "Accounts",
    "nav_sms": "SMS Processing",
    "nav_reports": "Reports",
    "nav_address": "Address Book",
    "nav_campaigns": "Campaign",

    "contact": "Contact",
    "download_pdf": "Download PDF",
    "title_main": "NATYABIP User Guide",
    "author": "Author",
    "version": "Version",

    "intro_desc": "This guide details the use of the NATYABIP SMS platform, covering dashboard management, profiles, accounts, SMS sending, reports, and campaigns, for a complete and effective handling.",

    "sec_dashboard": "I. Dashboard",
    "sec_profile": "II. Profile",
    "sec_accounts": "III. Accounts",
    "sec_sms": "IV. SMS Processing",
    "sec_reports": "V. Reports",
    "sec_address": "VI. Address Book",
    "sec_campaigns": "VII. Campaign",

    "dashboard_intro": "The dashboard presents a summary of the daily and monthly situation based on the selected account.",
    "key_features": "Key Features",
    "total_balance": "Total Balance:",
    "total_balance_desc": "Displays the global balance associated with the logged-in account.",
    "profile_space": "Profile Space:",
    "profile_space_desc": "Access to Profile section, logout, password management, and pricing.",
    "day_status": "Daily Status:",
    "day_status_desc": "Information based on the current date.",
    "month_status": "Monthly Status:",
    "month_status_desc": "Full interval of the current month or selected period.",
    "stats": "Statistics:",
    "stats_desc": "Message statistics, rates, and key indicators.",

    "profile_consult": "Profile Consultation",
    "profile_consult_desc": "View your profile card containing your basic information (Initials, Name, Email, Alert Threshold etc...).",
    "profile_edit": "Edit Information",
    "profile_edit_desc": "In the profile editing area, you can manage the following settings:",
    "field_company": "Company:",
    "field_company_desc": "Company name associated with the account.",
    "field_lastname": "Last Name:",
    "field_lastname_desc": "User's last name.",
    "field_firstname": "First Name:",
    "field_firstname_desc": "User's first name.",
    "field_email": "Email:",
    "field_email_desc": "Your contact email address.",
    "field_phone": "Cell Number:",
    "field_phone_desc": "Edit your phone number.",
    "field_sender": "Sender:",
    "field_sender_desc": "The default sender name.",
    "field_alert": "Alert Threshold:",
    "field_alert_desc": "Credit level to trigger an alert.",
    "field_longsms": "Long SMS:",
    "field_longsms_desc": "Enable sending of long SMS (concatenated).",
    "field_encoding": "Encoding Type:",
    "field_encoding_desc": "Character encoding (e.g. GSM7).",
    "field_billing": "Billing Mode:",
    "field_billing_desc": "Payment type (Prepaid or Postpaid).",
    "field_account_status": "Account Status:",
    "field_account_status_desc": "Current account situation (Active/Suspended).",
    "field_overdraft": "Overdraft Amount:",
    "field_overdraft_desc": "Authorized credit limit in case of overdraft.",
    "save_changes_info": "Click <strong>Save Changes</strong> to validate your updates.",

    "balance_history": "Balance History",
    "balance_history_desc": "Select the account, choose the date range (start/end), then click <strong>Search</strong> to view the balance history.",

    "header_balance": "Balance",
    "desc_balance": "Select the account, then click <strong>Search</strong> to view the balance.",

    "header_statement": "Statement",
    "desc_statement": "Select the account, then click <strong>Search</strong> to view the account statement.",

    "sender_id": "Sender ID",
    "sender_id_intro": "This area allows you to manage senders:",
    "consult": "Consult:",
    "consult_desc": "Filter by account or country.",
    "request": "Request:",
    "request_desc": "Enter the desired Sender ID then click <strong>VALIDATE</strong>.",
    "sender_note": "NB: Processing takes about three days.",
    "simple_send": "Simple Send",
    "send_steps": "To send an SMS:",
    "step_sender": "Select sender.",
    "step_recipient": "Enter recipient(s) (number with country code, e.g. 228XXXXXXXX). Separate multiple numbers with <strong>semicolons (;)</strong>.",
    "step_message": "Enter the message.",
    "step_validate": "Click <strong>VALIDATE</strong>.",
    "reports_intro": "View detailed reports on your sent messages.",
    "search_filters": "Search Filters",
    "filter_criteria": "Account / Country / Sender / Operator",
    "filter_criteria_desc": "Filter according to your needs.",
    "date_range": "Date Range",
    "date_range_desc": "Define the period.",
    "status": "Status",
    "status_desc": "Filter by (Accepted, Pending, Sent, Delivered, Confirmed, Rejected).",
    "search_buttons": "Use the <strong>Search</strong> button to view results or <strong>Cancel</strong> to reset.",
    "daily_situation": "Daily Situation",
    "daily_situation_desc": "Displays SMS status for a specific day after selecting account and date.",
    "add_contact": "Add Contact",
    "add_contact_desc": "Fill in Name, First Name, Prefix (e.g. 228) and Number. You can assign a category (e.g. Loyal Client) or create a new one. Click <strong>Save</strong>.",
    "import_search": "Import & Search",
    "import_search_desc": "Use the <strong>Import</strong> button to load contacts from an external file (Excel/CSV). Search by name or number and filter by period.",
    "create_campaign": "Create Campaign",
    "camp_step1": "Name your campaign.",
    "camp_step2": "Choose destination and sender.",
    "camp_step3": "Schedule date and time.",
    "camp_step4": "Write the message and import contacts (Excel).",
    "camp_step5": "<strong>Simulate</strong> to verify or validate.",

    "header_detail": "Detail",
    "desc_detail": "View campaign details (date, content, status).",

    "header_list": "List",
    "desc_list": "Filter and view the list of your campaigns.",

    "mod_active": "Modify / Activate Campaign",
    "mod_active_intro": "To modify or activate a campaign:",
    "mod_step1": "Select the campaign to modify.",
    "mod_step2": "Edit date/time or message if necessary.",
    "mod_step3": "Change campaign status:",
    "state_draft": "Draft:",
    "state_draft_desc": "Default status upon creation.",
    "state_active": "Active:",
    "state_active_desc": "Required to send/forward messages.",
    "state_done": "Finished / Cancelled:",
    "state_done_desc": "To close or cancel the campaign.",
    "mod_step4": "Save changes.",
    "active_note": "NB: Status must be set to <strong>Active</strong> for the message to be sent."
};
