window.translations_fr = {
    "user_guide": "Guide Utilisateur v1",
    "nav_intro": "Introduction",
    "nav_dashboard": "Tableau de Bord",
    "nav_profile": "Profil",
    "nav_accounts": "Comptes",
    "nav_sms": "Traitement SMS",
    "nav_reports": "Rapports",
    "nav_address": "Carnet d'Adresse",
    "nav_campaigns": "Campagne",

    "contact": "Contact",
    "download_pdf": "Télécharger en PDF",
    "title_main": "Guide d'Utilisation de NATYABIP",
    "author": "Rédaction",
    "version": "Version",

    "intro_desc": "Ce guide détaille l'utilisation de la plateforme NATYABIP SMS, couvrant la gestion du tableau de bord, des profils, des comptes, l'envoi de SMS, les rapports et les campagnes, pour une prise en main complète et efficace.",

    "sec_dashboard": "I. Tableau de Bord",
    "sec_profile": "II. Profil",
    "sec_accounts": "III. Comptes",
    "sec_sms": "IV. Traitement SMS",
    "sec_reports": "V. Rapports",
    "sec_address": "VI. Carnet d'Adresse",
    "sec_campaigns": "VII. Campagne",

    "dashboard_intro": "Le tableau de bord présente un résumé de la situation du jour et du mois en fonction du compte sélectionné.",
    "key_features": "Fonctionnalités Clés",
    "total_balance": "Solde Total :",
    "total_balance_desc": "Affiche le solde global associé au compte connecté.",
    "profile_space": "Espace Profil :",
    "profile_space_desc": "Accès à la section Profil, déconnexion, gestion du mot de passe et tarification.",
    "day_status": "Situation du Jour :",
    "day_status_desc": "Informations basées sur la date actuelle.",
    "month_status": "Situation du Mois :",
    "month_status_desc": "Intervalle complet du mois en cours ou période sélectionnée.",
    "stats": "Statistiques :",
    "stats_desc": "Statistiques des messages, taux et indicateurs clés.",

    "profile_consult": "Consultation du Profil",
    "profile_consult_desc": "Vous pouvez visualiser votre profil contenant vos informations de base (Initiales, Nom, Email, Seuil d'alerte, etc...).",
    "profile_edit": "Modification des Informations",
    "profile_edit_desc": "Dans l'espace de modification de profil, vous pouvez gérer les paramètres suivants :",
    "field_company": "Société :",
    "field_company_desc": "Nom de l'entreprise associée au compte.",
    "field_lastname": "Nom :",
    "field_lastname_desc": "Nom de famille de l'utilisateur.",
    "field_firstname": "Prénom :",
    "field_firstname_desc": "Prénom de l'utilisateur.",
    "field_email": "Email :",
    "field_email_desc": "Votre adresse électronique de contact.",
    "field_phone": "Numéro Cellulaire :",
    "field_phone_desc": "Modifier votre numéro de téléphone.",
    "field_sender": "Expéditeur :",
    "field_sender_desc": "Le nom d'expéditeur par défaut.",
    "field_alert": "Seuil d'alerte :",
    "field_alert_desc": "Niveau de crédit pour déclencher une alerte.",
    "field_longsms": "Long SMS :",
    "field_longsms_desc": "Activation de l'envoi de SMS longs (concaténés).",
    "field_encoding": "Type d'Encodage :",
    "field_encoding_desc": "Encodage des caractères (ex: GSM7).",
    "field_billing": "Mode de facturation :",
    "field_billing_desc": "Type de paiement (Prépayé ou Postpayé).",
    "field_account_status": "Etat du compte :",
    "field_account_status_desc": "Situation actuelle du compte (Actif/Suspendu).",
    "field_overdraft": "Montant découvert :",
    "field_overdraft_desc": "Limite de crédit autorisée en cas de découvert.",
    "save_changes_info": "Cliquez sur <strong>Enregistrer les modifications</strong> pour valider vos changements.",

    "balance_history": "Historique Balance",
    "balance_history_desc": "Sélectionnez le compte concerné, choisissez la plage de dates (début/fin), puis cliquez sur <strong>Rechercher</strong> pour afficher l’historique de balance.",

    "header_balance": "Solde",
    "desc_balance": "Sélectionnez le compte concerné, puis cliquez sur <strong>Rechercher</strong> pour afficher le solde.",

    "header_statement": "Relevé",
    "desc_statement": "Sélectionnez le compte concerné, puis cliquez sur <strong>Rechercher</strong> pour afficher le relevé de compte.",

    "sender_id": "Expéditeur (Sender ID)",
    "sender_id_intro": "Cette zone permet de gérer les expéditeurs :",
    "consult": "Consulter :",
    "consult_desc": "Filtrer par compte ou pays.",
    "request": "Demande :",
    "request_desc": "Saisir le Sender ID souhaité puis cliquer sur <strong>VALIDER</strong>.",
    "sender_note": "NB : Le traitement prend environ trois jours.",
    "simple_send": "Envoi Simple",
    "send_steps": "Pour envoyer un SMS :",
    "step_sender": "Sélectionnez l’expéditeur.",
    "step_recipient": "Saisir le(s) destinataire(s) (numéro avec indicatif, ex: 228XXXXXXXX). Séparez les numéros multiples par des <strong>points-virgules (;)</strong>.",
    "step_message": "Saisir le message.",
    "step_validate": "Cliquez sur <strong>VALIDER</strong>.",
    "reports_intro": "Consultez les rapports détaillés sur vos envois.",
    "search_filters": "Filtres de Recherche",
    "filter_criteria": "Compte / Pays / Expéditeur / Opérateur",
    "filter_criteria_desc": "Filtrez selon vos besoins.",
    "date_range": "Plage de Date",
    "date_range_desc": "Définissez la période.",
    "status": "État",
    "status_desc": "Filtrer par (Accepté, En cours, Envoyé, Délivré, Confirmé, Rejeté).",
    "search_buttons": "Utilisez le bouton <strong>Rechercher</strong> pour afficher les résultats ou <strong>Annuler</strong> pour réinitialiser.",
    "daily_situation": "Situation Journalière",
    "daily_situation_desc": "Affiche la situation des SMS pour une journée donnée après sélection du compte et de la date.",
    "add_contact": "Ajouter un Contact",
    "add_contact_desc": "Remplissez les champs Nom, Prénom, Indicatif (ex. 228) et Numéro. Vous pouvez assigner une catégorie (ex. Client fidèle) ou en créer une nouvelle. Cliquez sur <strong>Enregistrer</strong>.",
    "import_search": "Importer & Rechercher",
    "import_search_desc": "Utilisez le bouton <strong>Importer</strong> pour charger des contacts depuis un fichier externe (Excel/CSV). Recherchez par nom ou numéro et filtrez par période.",
    "create_campaign": "Créer une Campagne",
    "camp_step1": "Donnez un nom à votre campagne.",
    "camp_step2": "Choisissez la destination et l'expéditeur.",
    "camp_step3": "Planifiez la date et l'heure.",
    "camp_step4": "Rédigez le message et importez les contacts (Excel).",
    "camp_step5": "<strong>Simulez</strong> pour vérifier ou validez.",

    "header_detail": "Détail",
    "desc_detail": "Consultez les détails de la campagne (date, contenu, état).",

    "header_list": "Liste",
    "desc_list": "Filtrez et visualisez la liste de vos campagnes.",

    "mod_active": "Modifier / Activer une Campagne",
    "mod_active_intro": "Pour modifier ou activer une campagne :",
    "mod_step1": "Sélectionnez la campagne à modifier.",
    "mod_step2": "Modifiez la date/heure ou le message si nécessaire.",
    "mod_step3": "Changez l'état de la campagne :",
    "state_draft": "Brouillon :",
    "state_draft_desc": "État par défaut à la création.",
    "state_active": "Active :",
    "state_active_desc": "Nécessaire pour envoyer/transférer les messages.",
    "state_done": "Terminée / Annulée :",
    "state_done_desc": "Pour clore ou annuler la campagne.",
    "mod_step4": "Enregistrez les modifications.",
    "active_note": "NB : L'état doit être sur <strong>Active</strong> pour que le message soit envoyé."
};
